### ISSUE TITLE
Export ATLAS exposures as a 3 week rolling window

### ISSUE THREAD

**Issue by thespacedoctor** [thespacedoctor/psat-ligo-planning#4]
Much the same as for PanSTARRS in issue #3. Here is the query I think is needed:

```sql
SELECT 
    `dec` AS `decDeg`,
    `texp` AS `exp_time`,
    `filt` AS `filter`,
    `mjd`,
    `ra` AS `raDeg`,
    mag5sig AS `limiting_magnitude`,
    `obj` AS `atlas_object_id`
FROM
    atlas_metadataddc
WHERE
    mjd > mjdnow -21
ORDER BY mjd DESC
```

Again mjdnow needs to be calculated to get the 3-week window.

If these are exported to CSV I can import them frequently into the `ligo_wave` database.

@genghisken

**Comment by genghisken** [comment]
Change last line to `obs` and `mjdnow` to `mjdnow()`

``` sql
    `obs` AS `expname`
FROM
    atlas_metadataddc
WHERE
    mjd > mjdnow() -21
ORDER BY mjd DESC
```

Since `obj` actually refers to the pointing name, which is fairly meaningless unless you really want it. `obs` is the exposure name, which is kind of useful.  The modified query works.

**Comment by thespacedoctor** [comment]
Thanks Ken. Could I please have the `obj` column too? Don't care at this stage what it is called. I use it to determine the uniqueness of coverage when determining coverage stats and selecting pointings to print on maps.

**Comment by genghisken** [comment]
The obj column now belatedly added!
